# Generated by Django 5.0.3 on 2024-08-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegisteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Roll_no', models.EmailField(max_length=254)),
                ('Mobile_No', models.IntegerField()),
                ('Address', models.TextField()),
                ('Pin_code', models.IntegerField()),
                ('Image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
