# Generated by Django 5.0.3 on 2024-08-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_studentregisteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregisteration',
            name='Roll_no',
            field=models.IntegerField(),
        ),
    ]
